/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LINKSRouteImport } from './routes/LINKS'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AiRouteImport } from './routes/ai'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PromptlibraryRouteImport } from './routes/promptlibrary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LINKSRoute = LINKSRouteImport.update({
  id: '/LINKS',
  path: '/LINKS',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptlibraryRoute = PromptlibraryRouteImport.update({
  id: '/promptlibrary',
  path: '/promptlibrary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/LINKS': typeof LINKSRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/library': typeof LibraryRoute
  '/links': typeof LinksRoute
  '/live': typeof LiveRoute
  '/projects': typeof ProjectsRoute
  '/promptlibrary': typeof PromptlibraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/LINKS': typeof LINKSRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/library': typeof LibraryRoute
  '/links': typeof LinksRoute
  '/live': typeof LiveRoute
  '/projects': typeof ProjectsRoute
  '/promptlibrary': typeof PromptlibraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/LINKS': typeof LINKSRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/library': typeof LibraryRoute
  '/links': typeof LinksRoute
  '/live': typeof LiveRoute
  '/projects': typeof ProjectsRoute
  '/promptlibrary': typeof PromptlibraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/LINKS'
    | '/about'
    | '/achievements'
    | '/ai'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/library'
    | '/links'
    | '/live'
    | '/projects'
    | '/promptlibrary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/LINKS'
    | '/about'
    | '/achievements'
    | '/ai'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/library'
    | '/links'
    | '/live'
    | '/projects'
    | '/promptlibrary'
  id:
    | '__root__'
    | '/'
    | '/LINKS'
    | '/about'
    | '/achievements'
    | '/ai'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/library'
    | '/links'
    | '/live'
    | '/projects'
    | '/promptlibrary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LINKSRoute: typeof LINKSRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AiRoute: typeof AiRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  LibraryRoute: typeof LibraryRoute
  LinksRoute: typeof LinksRoute
  LiveRoute: typeof LiveRoute
  ProjectsRoute: typeof ProjectsRoute
  PromptlibraryRoute: typeof PromptlibraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LINKS': {
      id: '/LINKS'
      path: '/LINKS'
      fullPath: '/LINKS'
      preLoaderRoute: typeof LINKSRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promptlibrary': {
      id: '/promptlibrary'
      path: '/promptlibrary'
      fullPath: '/promptlibrary'
      preLoaderRoute: typeof PromptlibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LINKSRoute: LINKSRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AiRoute: AiRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  LibraryRoute: LibraryRoute,
  LinksRoute: LinksRoute,
  LiveRoute: LiveRoute,
  ProjectsRoute: ProjectsRoute,
  PromptlibraryRoute: PromptlibraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
